name: Build and Publish Images

on:
  pull_request: 

env:
  PROJECT_ID: logical-contact-396619
  GAR_NAME: reading-tracker
  GAR_LOCATION: us-central-1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    
    steps:
      # actions/checkout MUST come before auth
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - id: Gcloud Auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS}}'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - id: gitversion
        name: Determine Version
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
        
      - name: Build Images
        run: |
          echo ${{ steps.gitversion.outputs.semVer }}
          gcloud auth configure-docker "${{ env.GAR_LOCATION }}-docker.pkg.dev"
          
          docker buildx build -f library-frontend -t libraryfrontend:build .
          docker image tag libraryfrontend:build us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-registry/services/library-frontend:${{ steps.gitversion.outputs.semVer }}
          docker push --all-tags us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-registry/services/library-frontend
          
          docker buildx build -f MyReadingTracker/MyReadingTracker -t librarybackend:build .
          docker image tag librarybackend:build us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-registry/services/library-backend:${{ steps.gitversion.outputs.semVer }}
          docker push --all-tags us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-registry/services/library-backend

