name: Build Services

on:
  pull_request: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    
    steps:
      # actions/checkout MUST come before auth
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS}}'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        
      - name: test
        run: |
          gcloud config get-value projec
      