name: Gatling Simulations

on:
  workflow_dispatch:

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Testing/Backend/API/Gatling
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Execute Gatling Simulations
        run: mvn clean install gatling:test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: gatling-report
          path: ./Testing/Backend/API/Gatling/target/gatling/
          retention-days: 30