name: Rest Assured Java API Automation CI

on:
  workflow_dispatch: 
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Testing/Backend/API/RestAssured
        
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '21'

    - name: Run docker-compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "./docker-compose.yml"

    - name: Execute regression test suite
      run: mvn clean test

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: './Testing/Backend/API/RestAssured/target/surefire-reports/*.xml'