name: Rest Assured Java API Automation CI

on:
  workflow_dispatch: 
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Testing/Backend/API/RestAssured
        
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '21'

    - name: Execute regression test suite
      run: mvn clean test

    - name: test
      run: |
        ls